[plugin]
repository = "https://github.com/MeowZWR/ChatTwo.git"
commit = "606e1072aa821c5cb33a617cbf594bcff2aed381"
owners = [
    "Infiziert90",
    "lojewalo",
    "MeowZWR"
]
project_path = "ChatTwo"
