[plugin]
repository = "https://github.com/MeowZWR/Browsingway.git"
commit = "c2c78a5eb7a5b1dce9120305b569b8fb5daa5ce1"
owners = ["Styr1x", "MeowZWR"]
project_path = "Browsingway"
changelog = """\
- 找runtime
- 汉化
- 鼠标悬停显示
"""
