[plugin]
# The open-source Git repository that your code is hosted on.
# Must be visible to the external web, but doesn't have to be GitHub.
# If `git clone` accepts it, it will work here, with the caveat that it
# must be accessible (i.e. no `git` or `ssh` URLs, as the agent cannot clone those)
repository = "https://github.com/Loskh/DcTraveler.git"
# The commit to check out and build from the repository.
commit = "5c01bc12d67284b8483a483da06c93a16c4f30d9"
# The people authorised to update this manifest (e.g. who can deploy updates). These are GitHub usernames.
owners = [
    "Loskh"
]
changelog = '''
- 适配2025/10/11服务器API改动'''


